In [1]:
import pandas as pd



In [2]:
lokesh=pd.read_csv("Dry_Bean_Dataset.csv")

In [3]:
lokesh

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653247  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.913358      0.007332      0.003147      0.834222      0.998724   
1         0.953861      0.006979      0.003564      0.909851      0.998430   
2         0.908774      0.007244      0.003048      0.825871      0.999066   
3         0.928329      0.007017      0.003215      0.861794      0.994199   
4         0.970516      0.006697      0.003665      0.941900      0.999166   
...            ...           ...           ...           ...           ...   
13606     0.801865      0.006858      0.001749      0.642988      0.998385   
13607     0.822252      0.006688      0.001886      0.676099      0.998219   
13608     0.822730      0.006681      0.001888      0.676884      0.996767   
13609     0.817457      0.006724      0.001852      0.668237      0.995222   
13610     0.784997      0.007001      0.001640      0.616221      0.998180   

          Class  
0         SEKER  
1         SEKER  
2         SEKER  
3         SEKER  
4         SEKER  
...         ...  
13606  DERMASON  
13607  DERMASON  
13608  DERMASON  
13609  DERMASON  
13610  DERMASON  

[13611 rows x 17 columns]

In [4]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

In [5]:
lokesh.head()

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395    610.291       208.178117       173.888747      1.197191   
1  28734    638.018       200.524796       182.734419      1.097356   
2  29380    624.110       212.826130       175.931143      1.209713   
3  30008    645.884       210.557999       182.516516      1.153638   
4  30140    620.134       201.847882       190.279279      1.060798   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1      0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2      0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3      0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4      0.333680       30417     195.896503  0.773098  0.990893   0.984877   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0     0.913358      0.007332      0.003147      0.834222      0.998724  SEKER  
1     0.953861      0.006979      0.003564      0.909851      0.998430  SEKER  
2     0.908774      0.007244      0.003048      0.825871      0.999066  SEKER  
3     0.928329      0.007017      0.003215      0.861794      0.994199  SEKER  
4     0.970516      0.006697      0.003665      0.941900      0.999166  SEKER

In [6]:
lokesh=lokesh.drop("ShapeFactor1",axis=1)

In [7]:
lokesh.head()

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395    610.291       208.178117       173.888747      1.197191   
1  28734    638.018       200.524796       182.734419      1.097356   
2  29380    624.110       212.826130       175.931143      1.209713   
3  30008    645.884       210.557999       182.516516      1.153638   
4  30140    620.134       201.847882       190.279279      1.060798   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1      0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2      0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3      0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4      0.333680       30417     195.896503  0.773098  0.990893   0.984877   

   Compactness  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0     0.913358      0.003147      0.834222      0.998724  SEKER  
1     0.953861      0.003564      0.909851      0.998430  SEKER  
2     0.908774      0.003048      0.825871      0.999066  SEKER  
3     0.928329      0.003215      0.861794      0.994199  SEKER  
4     0.970516      0.003665      0.941900      0.999166  SEKER

In [8]:
X=lokesh.iloc[:,0:13].values
Y=lokesh.iloc[:, 15].values
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)


In [9]:
X

array([[2.83950000e+04, 6.10291000e+02, 2.08178117e+02, ...,
        9.58027126e-01, 9.13357755e-01, 3.14728900e-03],
       [2.87340000e+04, 6.38018000e+02, 2.00524796e+02, ...,
        8.87033637e-01, 9.53860842e-01, 3.56362400e-03],
       [2.93800000e+04, 6.24110000e+02, 2.12826130e+02, ...,
        9.47849473e-01, 9.08774239e-01, 3.04773300e-03],
       ...,
       [4.21390000e+04, 7.59321000e+02, 2.81539928e+02, ...,
        9.18424091e-01, 8.22729703e-01, 1.88827100e-03],
       [4.21470000e+04, 7.63779000e+02, 2.83382636e+02, ...,
        9.07906457e-01, 8.17457451e-01, 1.85202500e-03],
       [4.21590000e+04, 7.72237000e+02, 2.95142741e+02, ...,
        8.88380369e-01, 7.84997193e-01, 1.63981200e-03]])

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
Y_train

array(['BARBUNYA', 'HOROZ', 'SIRA', ..., 'SIRA', 'DERMASON', 'BARBUNYA'],
      dtype=object)

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, solver = 'lbfgs', multi_class='auto')
classifier.fit(X_train,Y_train)

C:\Users\lokes\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [13]:
Y_pred = classifier.predict(X_test)

In [14]:
probs_y = classifier.predict_proba(X_test)

In [15]:
probs_y= np.round(probs_y,2)

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
print(cm)

[[216   0  17   0   2   3  17]
 [  0  92   0   0   0   0   0]
 [ 11   0 327   0   7   1   4]
 [  0   0   0 679   3   9  44]
 [  1   0  10   3 367   0   9]
 [  2   0   0   1   0 358  15]
 [  1   0   2  51  12   8 451]]


In [17]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(Y_test,Y_pred,average="macro")
recall = recall_score(Y_test,Y_pred,average="macro")
print('Precision:',precision)
print('Recall:',recall)

Precision: 0.9281525029769677
Recall: 0.9224792830389111


In [18]:
import numpy as np
from sklearn.metrics import f1_score
f1 = f1_score(Y_test,Y_pred,average="macro")
print('f1_score:',f1)

f1_score: 0.9249694802464387


In [19]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test,Y_pred)
print('Accuracy:',accuracy)

Accuracy: 0.9144326110907087


In [20]:
Y_pred

array(['DERMASON', 'DERMASON', 'DERMASON', ..., 'SEKER', 'BARBUNYA',
       'DERMASON'], dtype=object)

In [21]:
Y_train

array(['BARBUNYA', 'HOROZ', 'SIRA', ..., 'SIRA', 'DERMASON', 'BARBUNYA'],
      dtype=object)

In [24]:
prediction=pd.DataFrame({'Actual':Y_test,'predicted':Y_pred}).to_csv('prediction.csv')

In [1]:
import pickle